language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.3
  - nightly

sudo: false

env:
  global:
    - DEFAULT=1
    - PHPSTAN=0
    - COVERAGE=0

matrix:
  include:
    - php: 7.2
      env: PHPCS=1 DEFAULT=0
    - php: 7.2
      env: PHPSTAN=1 DEFAULT=0
    - php: 7.2
      env: COVERAGE=1 DEFAULT=0

  allow_failures:
    - php: nightly

  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini

install:
  - if [[ $PHPSTAN == 1 ]]; then composer require "phpstan/phpstan:^0.9"; fi

script:
  - if [[ $DEFAULT == 1 ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPCS == 1 ]]; then vendor/bin/phpcs src/ tests/; fi
  - if [[ $PHPSTAN == 1 ]]; then composer phpstan; fi
  - if [[ $COVERAGE == 1 ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=clover.xml; fi

after_success:
  - if [[ $COVERAGE == 1 ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
